### ISSUE TITLE
Unable to build because of FlatButtons

### ISSUE THREAD

**Issue by levydanqc** [telmedola/emoji_choose#1]
There are a lof of `FlatButton` in the source code and Flutter removed them from their sdk.

This errors is thrown:
```
Try correcting the name to the name of an existing method, or defining a method named 'FlatButton'.
```

You should replace all `FlatButton` with the new buttons.

**Comment by telmedola** [comment]
Hi, sorry for the delay.

Fixed in version 0.0.2
Thanks for opening the issue
